### ISSUE TITLE
Tried your example but measurements seems to be not right

### ISSUE THREAD

**Issue by borjaevo** [iamgeoknight/OpenLayersDynamicMeasurement#1]
I added the layer and the interactions, and it perfoms the measurements. But checking with places we already know the real size, the measure its doing its not right, its bigger. Like 40-50% bigger i think. For example, a field we know it has 1500m2, im getting 2800m2 with your tool.
Any ideas what is happening?

**Comment by iamgeoknight** [comment]
Use appropriate projection for your openlayers map.
Or there may be some formula miscalculation.
I will check it out.
Thanks for pointing this out.
I will definitely look at it.

**Comment by borjaevo** [comment]
I dont think the layers are bad projected because we have diferent layers from different sources and seems to fit ok. But I noticed the vector layer that is defined in your code has no defined projection. Maybe you have to?

**Comment by iamgeoknight** [comment]
Hello @borjaevo, in the code for getting area I was using geometry's default **getArea** method and the I was transforming it into relevant physical area using  formula.
Instead of using geometry's default **getArea** method, use **ol.sphere.getArea()** or **ol.sphere.getLenght()** to get area or line measurement and transform it using **calArea** or **calDistance** methods defined in script.js.
Same has been applied to this repo. Now the are measurement are coming correct.
Please check and confirm

**Comment by borjaevo** [comment]
Yes, that fixed the problem

**Comment by borjaevo** [comment]
Hi again, there is still an error in the code. Area is calculating ok, but lines are not adding well. This is the line you forgot to change to ol.sphere.getLength:
`//the calculates the length of a segment and position the overlay at the midpoint of it
    this.calDistance(this.partDistanceOverlay, partLine.getFlatMidpoint(), ol.sphere.getLength(partLine));  `

After changing this is 100% ok.

**Comment by iamgeoknight** [comment]
You are right, for line, I forgot to change. I will correct it.
Thanks for bringing this into consideration.

**Comment by borjaevo** [comment]
No problem ;) and thanks for the tool
